name: .NET CI/CD Pipeline (Local)

on:
  push:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '9.0.x'
  DOCKER_IMAGE: mvcapp
  DOCKER_TAG: latest

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Build
        run: |
          docker build -f dockerfile/Dockerfile -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
          docker tag ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} ${{ env.DOCKER_IMAGE }}:latest

  local-deploy:
    needs: docker-build
    runs-on: self-hosted  # 👈 Critical change for local deployment
    steps:
      - uses: actions/checkout@v4

      # PowerShell script to stop, remove, and run the Docker container
      - name: Stop and Remove Old Container (if any)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Continue'

          # Check if the container exists
          $container = docker ps -a -q -f "name=mvcapp"

          if ($container) {
              # Check if the container is running
              $isRunning = docker inspect -f '{{.State.Running}}' $container
              if ($isRunning -eq "true") {
                  Write-Host "Stopping the running container..."
                  docker stop mvcapp
              } else {
                  Write-Host "Container is already stopped."
              }

              Write-Host "Removing the container..."
              docker rm mvcapp
          } else {
              Write-Host "No container named 'mvcapp' exists."
          }

      # Run the new container
      - name: Run New Container
        run: |
          docker run -d -p 80:80 --name mvcapp ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
