name: .NET CI/CD Pipeline (Local)

on:
  push:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '9.0.x'
  DOCKER_IMAGE: mvcapp
  DOCKER_TAG: latest

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Build
        run: |
          docker build -f dockerfile/Dockerfile -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
          docker tag ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} ${{ env.DOCKER_IMAGE }}:latest

  local-deploy:
    needs: docker-build
    runs-on: self-hosted  # 👈 Critical change for local deployment
    steps:
      - uses: actions/checkout@v4

      # Stop and remove the old container (if it exists)
      - name: Stop and remove old container
        run: |
          try {
            docker stop mvcapp
          } catch {
            Write-Host "Container already stopped or does not exist."
          }
          try {
            docker rm mvcapp
          } catch {
            Write-Host "Container already removed or does not exist."
          }

      # Run the new container
      - name: Run new container
        run: |
          docker run -d -p 80:80 --name mvcapp mvcapp
